### ISSUE TITLE
Missing "https" protocol in "schemes"?

### ISSUE THREAD

**Issue by darosh** [Mermade/aws2openapi#3]
All the generated swagger specs have `"schemes": ["http"]` only. It should be probably `https` or both?

**Comment by MikeRalphson** [comment]
You're probably right. Do you have a reference?

**Comment by darosh** [comment]
There is `sslEnabled` config property in JavaScriptSDK: 
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#sslEnabled-property

It looks like the default value is `true`: 
https://github.com/aws/aws-sdk-js/blob/0642da0822e9699862a81e424af69152248bdf6a/ts/config.ts#L77

Used around http/https: 
https://github.com/aws/aws-sdk-js/search?utf8=%E2%9C%93&q=sslEnabled&type=

Sometimes enforced to true: 
https://github.com/aws/aws-sdk-js/blob/5880e725ca12f559fcead5cac2c305e55de1ccfb/lib/services/s3.js#L136

**Comment by darosh** [comment]
I noticed it because it looks like outstanding exception in  OpenAPI directory:

![image](https://user-images.githubusercontent.com/297320/31319512-bccf2d42-ac64-11e7-957e-25e58f6389b4.png)

**Comment by MikeRalphson** [comment]
https://aws.amazon.com/articles/1928

> Most AWS services accept HTTPS requests...

**Comment by MikeRalphson** [comment]
AWS APIs updated, deploying now. Thanks again!
