### ISSUE TITLE
Bad regex for Lambda S3Bucket Definition

### ISSUE THREAD

**Issue by bobby-brennan** [Mermade/aws2openapi#4]
[Here's the regex](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/amazonaws.com/lambda/2015-03-31/swagger.yaml#L1875)

That regex is matched by `foo(?<!.)` but not `foo`.  I think the second half of the regex, `\(\?<!\.\)`, is meant to be a lookahead or something...

**Comment by MikeRalphson** [comment]
Bad in what sense? It seems to be a valid ECMA-262 regex.

In the original AWS definition it was 

```json
{ "pattern":"^[0-9A-Za-z\\.\\-_]*(?<!\\.)$" }
```
and the output yaml is

```yaml
pattern: '^[0-9A-Za-z\.\-_]*\(\?<!\.\)$'
```

So it may have been mangled by `convertRegex`.

https://github.com/Mermade/aws2openapi/blob/5c3208167355eb8949e224add24fb0a770189d48/index.js#L183-L209

**Comment by bobby-brennan** [comment]
What's the standard for the AWS regex? It is indeed a valid regex, but the
(?<!.) part seems to have a different meaning for AWS than EMCA (see above)

**Comment by MikeRalphson** [comment]
I'm not sure - as their format is undocumented, but I've assumed it's POSIX BRE.

**Comment by MikeRalphson** [comment]
Use of native JS RegExp here

https://github.com/aws/aws-sdk-js/blob/c108474595ec8714f97e47439090bc775fb76a25/lib/param_validator.js#L161-L169

Seems to indicate it should be a standard ECMA 262 RegExp... but if it was mangled by `convertRegex` that means the RegExp constructor throws on it:

> SyntaxError: Invalid regular expression: /^[0-9A-Za-z\.\-_]*(?<!\.)$/: Invalid group

Perhaps all we can do is report it upstream?

**Comment by bobby-brennan** [comment]
If the original regexen are ECMA 262 already, why is `convertRegex` necessary?

The regex works properly in the aws-sdk, but the [regex in their JSON](https://github.com/aws/aws-sdk-js/blob/8913f6962740386a3aa2039fa2fea3310d2d7689/apis/lambda-2015-03-31.normal.json#L1868) does indeed throw an invalid group when passed to the RegExp constructor...

**Comment by MikeRalphson** [comment]
> If the original regexen are ECMA 262 already, why is convertRegex necessary?

Because a number of `patterns` in the AWS json files throw errors in the RegExp constructor* and I *assumed* it was because they were POSIX BREs not ECMA 262 REs. I think the first example I found showed up as BRE syntax in some tool or other.

*and I wanted the resultant OpenAPI definitions to pass validation.

Can you debug the SDK and see if/how it is managing to instantiate the regex?

The lambda client appears to the load the `min` version of the API definition, not the `normal` one, and the `min` version doesn't contain any `pattern` properties (or descriptions, or ...).

**Comment by bobby-brennan** [comment]
It looks like the JS client doesn't do any client-side validation actually. Invalid regexen still get sent to the server, which responds with:
```json
{"message":"1 validation error detected: Value 'foo&*' at 'code.s3Bucket' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[0-9A-Za-z\\.\\-_]*(?<!\\.)$"}
```

**Comment by bobby-brennan** [comment]
According to [this cheatsheet](http://www.rexegg.com/regex-quickstart.html), the regex in question is a negative look-behind which says that the string can't end in a `.`, so `foo-` is legal but not `foo.`.

I don't think JS has an equivalent to negative lookbehinds. I think the best solution is to strip the negative lookbehind, which would result in a regex that's more permissive than it should be, but would at least pass for valid strings.

**Comment by bobby-brennan** [comment]
If you're good with that solution I can send a PR

**Comment by MikeRalphson** [comment]
That would be great, thanks.

**Comment by MikeRalphson** [comment]
I think we can close this?
